Fix unused variable in ssl_finished_in_postprocess
Summary:
Fix the following compiler warning.
```
/home/lhuang04/upstream/library/ssl_tls13_generic.c: In function ‘ssl_finished_in_postprocess’:
/home/lhuang04/upstream/library/ssl_tls13_generic.c:2466:9: error: unused variable ‘ret’ [-Werror=unused-variable]
     int ret;
```

Test Plan:
Apply the following patch to disable `MBEDTLS_SSL_SRV_C` and build.
```
diff --git a/include/mbedtls/mbedtls_config.h b/include/mbedtls/mbedtls_config.h
index ffaa4e3ea..b2cb9a1e4 100644
--- a/include/mbedtls/mbedtls_config.h
+++ b/include/mbedtls/mbedtls_config.h
@@ -2908,7 +2908,7 @@
  *
  * This module is required for SSL/TLS server support.
  */
-#define MBEDTLS_SSL_SRV_C
+//#define MBEDTLS_SSL_SRV_C

 /**
  * \def MBEDTLS_SSL_TLS_C
```

Reviewers:

Subscribers:

Tasks:

Tags: